function GB_Help(cmd)
	if cmd == "" or cmd == nil then
        GB_Message("","sys")
        GB_Message("--------------------------------------","sys")
        GB_Message("Guild Banker v"..GB_VERSION,"sys")
        GB_Message("by Azinath-EmeraldDream","sys")
        GB_Message("--------------------------------------","sys")
		GB_Message("usage: /gb <command> <args>","sys")
		GB_Message("Type '/gb help <command>' for info on a specific gbh command.","sys")
		GB_Message("","sys")
		GB_Message("Available gb commands:","sys")
		GB_Message("   audit","sys")
		GB_Message("   cut","sys")
        GB_Message("   gbimport","sys")
		GB_Message("   balance","sys")
        GB_Message("   onotes","sys")
        GB_Message("   pnotes","sys")
        GB_Message("   scale","sys")
		GB_Message("   sync","sys")
        GB_Message("   gbimport","sys")
        GB_Message("   setminrank","sys")
    elseif cmd == "audit" then
        GB_Message("-----------------------------","sys")
        GB_Message("Guild Banker","sys")
        GB_Message("Audit","sys")
        GB_Message("-----------------------------","sys")
		GB_Message("usage: /gb audit [bounties|list|clear]","sys")
		GB_Message("Reads the guild bank money log and bounty list and updates Balance officer notes for all new transactions.","sys")		
		GB_Message("Requires officer note and guild info write permissions.","sys")
		GB_Message("Requires a guild bank money log and guild roster refresh.","sys")
		GB_Message("The optional 'list' argument will list all guild bank transactions THIS character has audited.","sys")
   		GB_Message("The optional 'clear' argument clears the audit history list for THIS character.","sys")	
	elseif cmd == "cut" then
        GB_Message("-----------------------------","sys")
        GB_Message("Guild Banker","sys")
        GB_Message("Bank Cut","sys")
        GB_Message("-----------------------------","sys")
		GB_Message("useage: /gb cut <0-1>","sys")
		GB_Message("Sets the guild bank %cut on all Balance deposits.","sys")
		GB_Message("Requires officer note and guild info write permission.","sys")	
	elseif cmd == "balance" then
        GB_Message("-----------------------------","sys")
        GB_Message("Guild Bounty Hunter","sys")
        GB_Message("Balance","sys")
        GB_Message("-----------------------------","sys")
		GB_Message("usage: /gb balance [report | set <player> <amount> | mod <player> <amount>]","sys")
		GB_Message("When called with no arguments, it prints the player's current balance amount.","sys")
		GB_Message("Using the 'report' option will print the balance for all guild members.","sys")
		GB_Message("'report' requires officer note read permission.","sys")
		GB_Message("'set' sets <player> balance equal to <amount> \(in copper\).","sys")
		GB_Message("'set' requires officer note write permission.","sys")
		GB_Message("'mod' adds <amount> to <player> balance. <amount> can be negative or positive \(in copper\).","sys")
		GB_Message("'mod' requires officer note write permission. ","sys")
		GB_Message("Both 'set' and 'mod' accept <player='all'> to apply balance changes to all guild members.","sys")
    elseif cmd == "onotes" then
        GB_Message("-----------------------------","sys")
        GB_Message("Guild Banker","sys")
        GB_Message("Officer Notes","sys")
        GB_Message("-----------------------------","sys")
		GB_Message("usage: /gb onotes save <tag> | load <tag> | list","sys")
		GB_Message("save <tag> saves the guild officer notes with the name <tag>.","sys")
        GB_Message("load <tag> loads the guild officer notes saved with the name <tag>.","sys")
        GB_Message("list displays the tags of all the saved officer notes.","sys")
    elseif cmd == "pnotes" then
        GB_Message("-----------------------------","sys")
        GB_Message("Guild Banker","sys")
        GB_Message("Public Notes","sys")
        GB_Message("-----------------------------","sys")
		GB_Message("usage: /gb pnotes save <tag> | load <tag> | list","sys")
		GB_Message("save <tag> saves the guild public notes with the name <tag>.","sys")
        GB_Message("load <tag> loads the guild public notes saved with the name <tag>.","sys")
        GB_Message("list displays the tags of all the saved public notes.","sys")
	elseif cmd == "sync" then 
        GB_Message("-----------------------------","sys")
        GB_Message("Guild Banker","sys")
        GB_Message("Sync","sys")
        GB_Message("-----------------------------","sys")
		GB_Message("usage: /gb sync","sys")
		GB_Message("Forces a resynchronization of your bounty list with all online guild members.","sys")
		GB_Message("This is done automatically on entering the game world and on UI reload.","sys")
    
    elseif cmd == "gbimport" then
        GB_Message("-----------------------------","sys")
        GB_Message("Guild Banker","sys")
        GB_Message("Guild Bank Import","sys")
        GB_Message("-----------------------------","sys")
        GB_Message("usage: /gb gbimport [<discount>]","sys")
        GB_Message("Imports all items in the currently selected guild bank tab into the GBH item list with prices from the Auctionator addon.","sys")
        GB_Message("If <discount> is provided, it will apply it to the Auctionator prices.","sys")
        
    elseif cmd == "setminrank" then
        GB_Message("-----------------------------","sys")
        GB_Message("Guild Banker","sys")
        GB_Message("Set Minimum Officer Rank","sys")
        GB_Message("-----------------------------","sys")
        GB_Message("usage: /gb setminrank <rankindex>","sys")
        GB_Message("Sets the minimum officer rank for enforcing Officer Locked bounties.","sys")
        GB_Message("GBH will not accept any bounty updates from players who's rank index is greater than <rankindex>.","sys")
    elseif cmd == "scale" then
        GB_Message("-----------------------------","sys")
        GB_Message("Guild Banker","sys")
        GB_Message("Set Guild Banker UI Scale","sys")
        GB_Message("-----------------------------","sys")
        GB_Message("usage: /gb scale <0-1>","sys")
        GB_Message("Sets the scale of the main Guild Banker UI frame.","sys")    
	end
end
